# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name=b'Form field name')),
                ('value', models.CharField(max_length=50, verbose_name=b'Form field value')),
                ('description', models.CharField(max_length=50, verbose_name=b'Form field description')),
            ],
        ),
    ]
