# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freefolks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicoption',
            name='field_name',
            field=models.CharField(choices=[(b'bank', b'Bank'), (b'transaction_type', b'Transaction Type')], max_length=50, verbose_name=b'Form field name'),
        ),
    ]
