# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freefolks', '0002_auto_20180602_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name=b'User name')),
                ('bank_name', models.CharField(max_length=50, verbose_name=b'Enter your bank')),
                ('branch', models.CharField(max_length=200, verbose_name=b'Branch name')),
                ('account_number', models.CharField(max_length=200, null=True, verbose_name=b'Account number')),
                ('access_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=b'Title')),
                ('transaction_type', models.CharField(max_length=50, verbose_name=b'Transaction type')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('access_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freefolks.Accounts')),
            ],
        ),
    ]
