# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freefolks', '0003_accounts_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
