# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freefolks', '0006_auto_20180602_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockpile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name=b'Title for stockpile')),
                ('stockpile_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Stockpile date')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Stockpile amount')),
                ('number_of_stockpile', models.IntegerField(default=20, verbose_name=b'Number of Stockpile')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'Description of Stockpile')),
                ('access_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stockpiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, verbose_name=b'Title for stockpile with month')),
                ('stockpile_number', models.CharField(choices=[(1, b'stockpile_1'), (2, b'stockpile_2'), (3, b'stockpile_3'), (4, b'stockpile_4'), (5, b'stockpile_5'), (6, b'stockpile_6'), (7, b'stockpile_7'), (8, b'stockpile_8'), (9, b'stockpile_9'), (10, b'stockpile_10'), (11, b'stockpile_11'), (12, b'stockpile_12'), (13, b'stockpile_13'), (14, b'stockpile_14'), (15, b'stockpile_15'), (16, b'stockpile_16'), (17, b'stockpile_17'), (18, b'stockpile_18'), (19, b'stockpile_19'), (20, b'stockpile_20'), (21, b'stockpile_21')], max_length=50, verbose_name=b'Transaction type')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name=b'Stockpile amount paid')),
                ('grand_taken', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name=b'Stockpile amount paid')),
                ('stockpile_month', models.DateTimeField(blank=True, null=True, verbose_name=b'Stockpile monthly date')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freefolks.Stockpile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name=b'Vendor name')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Vendor phone number')),
                ('address', models.TextField(blank=True, null=True, verbose_name=b'Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Account number'),
        ),
        migrations.AddField(
            model_name='stockpile',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freefolks.Vendor'),
        ),
    ]
