# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freefolks', '0007_auto_20180603_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockpiling',
            old_name='vendor',
            new_name='stockpile',
        ),
        migrations.AlterUniqueTogether(
            name='stockpiling',
            unique_together=set([('stockpile', 'stockpile_number')]),
        ),
    ]
